config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search', to: 'lines#search'
  post 'search', to: 'lines#start'
  resources :lines
  resources :destinations
  resources :carriers

end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :line_type
  belongs_to :carrier
  belongs_to :day
  has_many :destinations_lines, :dependent => :destroy
  has_many :destinations, through: :destinations_lines
  # accepts_nested_attributes_for :destinations_lines, :allow_destroy => true
  # accepts_nested_attributes_for :destinations

  def destination_tokens
    self.destination_ids
  end

  def destination_tokens=(tokens)
    self.destination_ids = Destination.ids_from_tokens(tokens)
  end


end

app/models/line_type.rb
class LineType < ActiveRecord::Base
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :authenticate_user!, except: [:search, :start]
  before_action :set_line, only: [:show, :edit, :update, :destroy]


  layout 'public', only: [:start, :search]


  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    #my_time =  "#{line_params['start_time(4i)']}:#{line_params['start_time(5i)']}"
    @line = Line.new(line_params)
    #@line.start_time = my_time.to_s

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search

  end

  def start
    if params[:query].present? && params[:destination_id].present?
      dest = Destination.find(params[:destination_id])
      datum = Date.strptime(params[:query].to_s, '%m/%d/%Y')
      day = datum.strftime('%A')
      day_id = Day.find_by_name(day.to_s).id
      @lines = dest.lines
      @lines = @lines.where(day_id: day_id)

      @lines = @lines.where(carrier_id: params[:carrier_id]) if !params[:carrier_id].blank?
      @lines = @lines.where(line_type_id: params[:line_type_id]) if !params[:line_type_id].blank?
    else
      @lines = nil
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      # params.require(:line).permit(:cost, :line_type_id, :carrier_id, :day_id, :destination_id, :start_time,
      #                              destinations_lines_attributes: [:id, :_destroy, :destination_id,
      #                                                              destination_attributes: [:id, :name, :_destroy]])
      params.require(:line).permit(:cost, :line_type_id, :carrier_id, :day_id, :start_time, :destination_tokens)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :line_type_id %><br>
    <%= f.collection_select :line_type_id, LineType.all, :id, :name, {prompt: 'Choose LineType'} %>
  </div>
  <div class="field">
    <%= f.label :carrier_id %><br>
    <%= f.collection_select :carrier_id, Carrier.all, :id, :name, {prompt: 'Choose Carrier'} %>
  </div>
  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.collection_select :day_id, Day.all, :id, :name, {prompt: 'Choose day'} %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :destination_tokens %><br/>
    <%= f.text_field :destination_tokens, data: {load: @line.destinations} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/_lines.html.erb
<% if @lines && !@lines.empty?%>
<table class="table">
  <thead>
    <td>Lyne Type</td>
    <td>Carrier</td>
    <td>Cost</td>
    <td>Destinations</td>
  </thead>
  <% @lines.each do |line|%>
    <tr>
      <td> <%= line.line_type.name%> </td>
      <td> <%= line.carrier.name%> </td>
      <td> <%= line.cost%> </td>
      <td>
        <ul>
            <%line.destinations.each do |destination| %>
                <li> <%= destination.name %> </li>
            <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
</table>
<% else %>
    <p>No result's found</p>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lines</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cost</th>
      <th>Line type</th>
      <th>Carrier</th>
      <th>Day</th>
      <th>Destinations</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.cost %></td>
        <td><%= line.line_type.name %></td>
        <td><%= line.carrier.name %></td>
        <td><%= line.day.name %></td>
        <td>
          <ul>
            <%line.destinations.each do |destination|%>
                <li><%= destination.name %></li>
            <% end %>
          </ul>
        </td>
        <td><%= line.start_time %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/search.html.erb
<h1>Searching lines</h1>

<%= form_tag('/search', remote: true) do %>
    <%= label_tag 'Carrier' %>
    <%= select_tag 'carrier_id', options_from_collection_for_select(Carrier.all, :id, :name), {prompt: "Any"}%>
    <%= label_tag 'Line Type'%>
    <%= select_tag 'line_type_id', options_from_collection_for_select(LineType.all, :id, :name), {prompt: "Any"}%>
    <%= label_tag 'Destination*' %>
    <%= select_tag 'destination_id', options_from_collection_for_select(Destination.all, :id, :name), {prompt: 'Choose Destination'}%>
    <%= label_tag 'Date*' %>
    <%= text_field_tag :query, params[:query], class: 'datepicker' %>
    <%= submit_tag 'Search', :name => nil %>
<% end %>

<br/>

<div class="results"></div>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost:</strong>
  <%= @line.cost %>
</p>

<p>
  <strong>Line type:</strong>
  <%= @line.line_type.name %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @line.carrier.name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @line.day.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @line.start_time %>
</p>

<p>
  <strong>Destinations</strong>
  <ul>
    <% @line.destinations.each do |destination| %>
        <li><%= destination.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>

app/views/lines/start.js.erb
$('.results').html('<%= escape_javascript(render("lines")) %>');
$('.results').show();