config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search', to: 'lines#search'
  post 'search', to: 'lines#start'
  resources :lines
  resources :destinations
  resources :carriers

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_carrier, only: [:show, :edit, :update, :destroy]

  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.all
  end

  # GET /carriers/1
  # GET /carriers/1.json
  def show
  end

  # GET /carriers/new
  def new
    @carrier = Carrier.new
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = Carrier.new(carrier_params)

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to @carrier, notice: 'Carrier was successfully created.' }
        format.json { render :show, status: :created, location: @carrier }
      else
        format.html { render :new }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1
  # PATCH/PUT /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier.destroy
    respond_to do |format|
      format.html { redirect_to carriers_url, notice: 'Carrier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrier_params
      params.require(:carrier).permit(:name)
    end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/views/carriers/_form.html.erb
<%= form_for(@carrier) do |f| %>
  <% if @carrier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrier.errors.count, "error") %> prohibited this carrier from being saved:</h2>

      <ul>
      <% @carrier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carriers/edit.html.erb
<h1>Editing Carrier</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrier %> |
<%= link_to 'Back', carriers_path %>

app/views/carriers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carriers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carriers.each do |carrier| %>
      <tr>
        <td><%= carrier.name %></td>
        <td><%= link_to 'Show', carrier %></td>
        <td><%= link_to 'Edit', edit_carrier_path(carrier) %></td>
        <td><%= link_to 'Destroy', carrier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrier', new_carrier_path %>

app/views/carriers/new.html.erb
<h1>New Carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carrier.name %>
</p>

<%= link_to 'Edit', edit_carrier_path(@carrier) %> |
<%= link_to 'Back', carriers_path %>