config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search', to: 'lines#search'
  post 'search', to: 'lines#start'
  resources :lines
  resources :destinations
  resources :carriers

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :destinations_lines
  has_many :lines, through: :destinations_lines

  def self.tokens(query)
    destinations = where("name like ?", "%#{query.titleize}%")
    if destinations.empty?
      [{id: "<<<#{query}>>>", name: "New \"#{query}\""}]
    else
      destinations
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1.titleize).id}
    tokens.split(',')
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
    respond_to do |format|
      format.html
      format.json {render json: @destinations.tokens(params[:q]), only: [:id, :name]}
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name)
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.name %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination.name %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>