config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search', to: 'lines#search'
  post 'search', to: 'lines#start'
  resources :lines
  resources :destinations
  resources :carriers

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bus Station</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand"></div>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to 'Destinations', destinations_path%> </li>
          <li> <%= link_to 'Carriers', carriers_path %> </li>
          <li> <%= link_to 'Lines', lines_path%> </li>
          <% if user_signed_in?%>
            <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
          <% end %>
        </ul>
  </div>
</nav>
<% flash.each do |name, msg|%>
    <%= content_tag :div, msg, class: name%>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bus Station</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg|%>
    <%= content_tag :div, msg, class: name%>
<% end %>

<%= yield %>

</body>
</html>